<?php

namespace Doctrine\Proxies\__CG__\app\models;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Profile extends \app\models\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function beforePersist()
    {
        $this->__load();
        return parent::beforePersist();
    }

    public function beforeUpdate()
    {
        $this->__load();
        return parent::beforeUpdate();
    }

    public function __get($field)
    {
        $this->__load();
        return parent::__get($field);
    }

    public function __set($field, $value)
    {
        $this->__load();
        return parent::__set($field, $value);
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function getErrors()
    {
        $this->__load();
        return parent::getErrors();
    }

    public function addCondition($condition)
    {
        $this->__load();
        return parent::addCondition($condition);
    }

    public function toArray($joins = array (
))
    {
        $this->__load();
        return parent::toArray($joins);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fullname', 'address', 'phone');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}